### PR TITLE
Add shutdown to daemon (fix RpcIO error in CI)

### LINKED ISSUE #78: CI tests hang on RpcIO error
`Error: 1-11T00:42:06.812][ERROR][atelier_loader::rpc_io] Error connecting RpcIO: Connection refused (os error 61)`

This error is preventing tests from completing in CI.

I believe we should:

- Limit connection attempts in CI or number of retries
- Attempt to solve underlying issue.

### PR DESCRIPTION
**Pull request by ezpuzz**
fixes #78 

I'm pretty amateur when it comes to tokio but after wrangling with it most of today I think this might help with the CI tests?

Let me know if i've made a threading foul.

Also this will make CI tests slightly more verbose which I think is particularly helpful for this project.

The changes in file_tracker.rs are primarily moving things around to be more readable from top to bottom.

### CODE REVIEW

**Comment by ezpuzz** [comment]
I don't understand why the last commit didn't trigger CI but you can see the tests pass.  I am having an issue with the tests in amethyst though so this may not be ready...

**Comment by ezpuzz** [comment]
aha!  the failing log says this : `thread '<unnamed>' panicked at 'failed to create asset db: Lmdb(Other(17))', daemon/src/daemon.rs:186:55`

**Comment by ezpuzz** [comment]
so it's a filesystem error on accessing `.assets_db`.  The tests have to be serial to avoid this.

**Comment by ezpuzz** [comment]
nope that didn't work, at this point I am kinda stumped.  maybe serial_test is doing something to threads? idk

**Comment by kabergstrom** [comment]
Thank you for trying a few different things, I'll try to pick this up and figure out how to ensure everything is cleaned up when daemon::run returns.

**Comment by ezpuzz** [comment]
I think the daemon might be fine in this case. the first test is failing in ci due to something hanging in the loader?

**Comment by ezpuzz** [comment]
ayyy :)

**Comment by kabergstrom** [comment]
Wow that's a whole lot of stuff! Glad you managed to clean up the tokio/futures cruft with some new stuff.

Thanks for the heroic effort!

**Pull request merged**
